version: '{build}'
skip_tags: true
image: Visual Studio 2017
configuration: Release
before_build:
- msbuild src\CodeGeneration.Roslyn.sln /nologo /m /v:quiet /t:restore
build_script:
- msbuild src\CodeGeneration.Roslyn.sln /nologo /m /v:minimal /t:build,pack
artifacts:
- path: bin\**\*.nupkg
  name: NuGet Package
