version: '{build}'
skip_tags: true
image:
- Visual Studio 2017
- Ubuntu
configuration: Release
build_script:
- cmd: msbuild src/CodeGeneration.Roslyn.sln /nologo /m /v:minimal /restore /t:build,pack
- sh: dotnet build src/CodeGeneration.Roslyn.Tests/CodeGeneration.Roslyn.Tests.csproj -f netcoreapp2.1
artifacts:
- path: bin/**/*.nupkg
  name: NuGet Package
