trigger:
  branches:
    include: ["master"]
  paths:
    exclude: ["doc", "*.md", ".appveyor.yml", ".travis.yml"]

variables:
#  TreatWarningsAsErrors: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: Release
  BuildPlatform: Any CPU

resources:
  containers:
  - container: xenial
    image: andrewarnott/linux-buildagent

jobs:
- job: Windows
  pool: Hosted VS2017
  steps:
  - task: DotNetCoreInstaller@0
    displayName: Install/select .NET Core SDK
    inputs:
      version: '2.1.500'

  - script: |
      dotnet tool install --tool-path . nbgv
      .\nbgv cloud -p src
    displayName: Set build number
    condition: ne(variables['system.pullrequest.isfork'], true)

  - script: dotnet --info
    displayName: Show dotnet SDK info

  - task: DotNetCoreCLI@2
    displayName: Restore NuGet packages
    inputs:
      command: restore
      verbosityRestore: normal # detailed, normal, minimal
      projects: src/**/*.sln
      feedsToUse: config
      nugetConfigPath: src/nuget.config

  # Use VSBuild on Windows so GitLink will work (it fails on dotnet build)
  # Also targeting net20, net40, PCLs etc requires full MSBuild
  - task: VSBuild@1
    displayName: Build Visual Studio solution
    inputs:
      vsVersion: '15.0'
      solution: src/**/*.sln
      msbuildArgs: /t:build,pack /m /v:m /bl:"$(Build.ArtifactStagingDirectory)/build_logs/msbuild.binlog"
      platform: $(BuildPlatform)
      configuration: $(BuildConfiguration)

  - task: DotNetCoreCLI@2
    displayName: Run tests
    inputs:
      command: test
      workingDirectory: src
      arguments: -v n --no-build -c $(BuildConfiguration)

  - task: CopyFiles@1
    displayName: Collecting project.assets.json artifacts
    inputs:
      Contents: |
        obj/**/project.assets.json
      TargetFolder: $(Build.ArtifactStagingDirectory)/projectAssetsJson
    condition: succeededOrFailed()

  - task: CopyFiles@1
    displayName: Collecting deployables
    inputs:
      Contents: |
        bin/**/$(BuildConfiguration)/**/*.nupkg
      TargetFolder: $(Build.ArtifactStagingDirectory)/deployables
      flattenFolders: true

  - task: PublishBuildArtifacts@1
    displayName: Publish projectAssetsJson artifacts
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)/projectAssetsJson
      ArtifactName: projectAssetsJson
      ArtifactType: Container
    condition: and(succeededOrFailed(), ne(variables['system.pullrequest.isfork'], true))

  - task: PublishBuildArtifacts@1
    displayName: Publish build_logs artifacts
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)/build_logs
      ArtifactName: build_logs
      ArtifactType: Container
    condition: and(succeededOrFailed(), ne(variables['system.pullrequest.isfork'], true))

  ## The rest of these steps are for deployment and skipped for PR builds

  #- task: PublishBuildArtifacts@1
  #  inputs:
  #    PathtoPublish: $(build.sourcesdirectory)/bin
  #    ArtifactName: bin
  #    ArtifactType: Container
  #  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), ne(variables['system.pullrequest.isfork'], true))

  - task: PublishBuildArtifacts@1
    displayName: Publish deployables artifacts
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)/deployables
      ArtifactName: deployables
      ArtifactType: Container
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), ne(variables['system.pullrequest.isfork'], true))

- job: Linux
  pool:
    vmImage: Ubuntu 16.04
  container: xenial
  variables:
    GitLinkEnabled: false
  steps:
  - template: azure-pipelines/testfx.yml
    parameters:
      projectdirectory: src/CodeGeneration.Roslyn.Tests

- job: macOS
  pool:
    vmImage: macOS 10.13
  variables:
    GitLinkEnabled: false
  steps:
  - template: azure-pipelines/testfx.yml
    parameters:
      projectdirectory: src/CodeGeneration.Roslyn.Tests
