steps:
- task: UseDotNet@2
  displayName: Install/select .NET Core SDK
  inputs:
    useGlobalJson: true
- script: dotnet restore
  displayName: Restore packages
  workingDirectory: ${{ parameters.projectdirectory }}
- script: dotnet build -v n -c $(BuildConfiguration) --no-restore /bl:"$(Build.ArtifactStagingDirectory)/build_logs/build.binlog"
  displayName: Build
  workingDirectory: ${{ parameters.projectdirectory }}
- script: dotnet test -v n -c $(BuildConfiguration) --no-build
  displayName: Run tests
  workingDirectory: ${{ parameters.projectdirectory }}
